version: "3.9"
services:
    mongo:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=openliberty
        ports:
            - "27017:27017"
        volumes:
            - ~/mongo/data:/data/db
            - "./leaderboard/assets/:/docker-entrypoint-initdb.d/"
        command: mongod
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ~/prometheus:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        depends_on:
            - gameservice
        ports:
            - "9090:9090"
    grafana:
        image: grafana/grafana:7.3.7
        user: "1000"
        container_name: grafana
        volumes:
            - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
            - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
            - ./grafana/dashboards/open-liberty_rev5.json:/var/lib/grafana/dashboards/open-liberty_rev5.json
            - ./grafana/dashboards/space-rover-rev1.json:/var/lib/grafana/dashboards/space-rover-rev1.json
        depends_on:
            - prometheus
        ports:
            - "3010:3000"
    leaderboard:
        build: ./leaderboard
        ports:
            - "9080:9080"
    gameservice:
        build: ./game
        ports:
            - "9070:9080"
    client:
        build:
            context: ./client
            args:
                - GAME_URL=http://localhost:9070/game
                - GAME_SOCKET_URL=ws://localhost:9070/roversocket
                - GAME_DURATION_SECONDS=120
                - LEADERBOARD_URL=http://localhost:9080/mongo/leaderboard
        ports:
            - "3000:80"
    mockrover:
        build: ./mock/rover
        ports:
            - "5045:5045"
    mockboard:
        build: ./mock/board
        ports:
            - "5046:5045"
